name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container
        run: |
          docker build -f Dockerfile.prod -t python-crud:prod .
          echo "Build container"

      - name: Save image
        run: |
          docker save -o /tmp/python-crud-prod.tar python-crud:prod
          echo "Save image to tar-archive"

      - name: Verify SSH Host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Deploy to server
        uses: D3rHase/ssh-command-action@latest
        with:
          port: ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            podman load -i /tmp/python-crud-prod.tar
            podman stop python-crud-prod || true
            podman rm python-crud-prod || true
            podman rmi python-crud:prod || true
            podman run -d --name python-crud-prod --network host python-crud:prod
            echo "Container has been executed"

