name: Developing

on:
  push:
    branches: ["dev"]

jobs:
  test:
    runs-on: ubuntu:latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: kubsu
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
        run: "Checkout code"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        run: echo "Setup docker buildx"

      - name: Build container
        run: |
          docker build -f Dockerfile.dev -t $REPO_NAME:dev .
          echo "Creating application container"

      - name: Run tests
        run: docker run --rm --network=host $REPO_NAME:dev
        echo "Running tests"
